stages:
  prepare:
    cmd: python3.12 src/prepare.py data/raw data/prepared
    deps:
      - data/raw
      - src/prepare.py
      - src/utils/seed.py
    params:
      - prepare
    outs:
      - data/prepared

  hitl_prepare:
    cmd: python3.12 src/hitl_prepare.py data/uncertain_images data/ data/annotations_hitl1.csv
    deps:
      - data/uncertain_images
      - data/annotations_hitl1.csv
      - src/hitl_prepare.py
      - src/utils/seed.py
      - data/prepared
    params:
      - prepare
    outs:
      - data/hitl

  hitl_train:
    cmd: python3.12 src/hitl_train.py data/prepared data/prepared_hitl model
    deps:
      - data/prepared_hitl
      - data/prepared
      - src/hitl_train.py
      - src/utils/seed.py
    params:
      - train
    outs:
      - model

  hitl_evaluation:
    cmd: python3.12 src/evaluate.py model data/prepared
    deps:
      - model
      - data/prepared
      - src/evaluate.py
    metrics:
      - evaluation/metrics.json
    plots:
      - evaluation/plots/confusion_matrix.png
      - evaluation/plots/pred_preview.png
      - evaluation/plots/training_history.png 
